"""empty message

Revision ID: 01a06eb785db
Revises: 
Create Date: 2021-03-28 17:10:25.961771

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01a06eb785db'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reply',
    sa.Column('reply_id', sa.Integer(), nullable=False),
    sa.Column('userid', sa.String(length=32), nullable=False),
    sa.Column('replies', sa.Text(), nullable=False),
    sa.Column('time', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('reply_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reply')
    # ### end Alembic commands ###
